spring.config.import=optional:file:.env.local[.properties]

server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}

spring.flyway.enabled=${FLYWAY_ENABLED:true}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.redis.session.ttl-seconds=${SESSION_TTL_SECONDS:1800}
spring.redis.session.ttl-refresh-threshold-seconds=${SESSION_TTL_REFRESH_THRESHOLD_SECONDS:300}
spring.redis.session.session-cookie-name=${SESSION_COOKIE_NAME:SESSION_ID}

server.tomcat.max-swallow-size=${TOMCAT_MAX_SWALLOW_SIZE:-1}
server.tomcat.max-part-count=${TOMCAT_MAX_PART_COUNT:500}
server.tomcat.max-http-form-post-size=${TOMCAT_MAX_HTTP_FORM_POST_SIZE:120MB}

spring.servlet.multipart.enabled=${MULTIPART_ENABLED:true}
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:100MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:120MB}

spring.minio.url=${MINIO_URL}
spring.minio.access-key=${MINIO_ACCESS_KEY}
spring.minio.secret-key=${MINIO_SECRET_KEY}
spring.minio.bucket=${MINIO_BUCKET}

springdoc.swagger-ui.enabled = ${SWAGGER_ENABLED:true}
springdoc.api-docs.enabled=${OPEN_API_ENABLED:true}
